name: about_weather
description: A new Flutter application about weather.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  amap_flutter_location: ^2.0.0
  dio: ^4.0.0
  json_annotation: ^4.0.1
  provider: ^5.0.0
  intl: ^0.17.0
  webview_flutter: ^2.0.9
  flutter_html: ^2.1.0
  shared_preferences: ^2.0.6
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  # intl_translation: ^0.17.10+1

# dependency_overrides:
#   intl: ^0.16.1
#   analyzer: ^0.41.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/W0.png
    - lib/images/W1.png
    - lib/images/W2.png
    - lib/images/W3.png
    - lib/images/W4.png
    - lib/images/W5.png
    - lib/images/W6.png
    - lib/images/W7.png
    - lib/images/W8.png
    - lib/images/W9.png
    - lib/images/W10.png
    - lib/images/W13.png
    - lib/images/W14.png
    - lib/images/W15.png
    - lib/images/W16.png
    - lib/images/W17.png
    - lib/images/W18.png
    - lib/images/W19.png
    - lib/images/W20.png
    - lib/images/W29.png
    - lib/images/W30.png
    - lib/images/W31.png
    - lib/images/W32.png
    - lib/images/W33.png
    - lib/images/W34.png
    - lib/images/W35.png
    - lib/images/W36.png
    - lib/images/W44.png
    - lib/images/W45.png
    - lib/images/W46.png
    - lib/images/B0.webp
    - lib/images/B1.webp
    - lib/images/B2.webp
    - lib/images/B3.webp
    - lib/images/B4.webp
    - lib/images/B5.webp
    - lib/images/B6.webp
    - lib/images/B7.webp
    - lib/images/B8.webp
    - lib/images/B9.webp
    - lib/images/B10.webp
    - lib/images/B11.webp
    - lib/images/B12.webp
    - lib/images/B13.webp
    - lib/images/B14.webp
    - lib/images/B15.webp
    - lib/images/B16.webp
    - lib/images/B17.webp
    - lib/images/B18.webp
    - lib/images/B19.webp
    - lib/images/B20.webp
    - lib/images/B21.webp
    - lib/images/B22.webp
    - lib/images/B23.webp
    - lib/images/B24.webp
    - lib/images/B25.webp
    - lib/images/B26.webp
    - lib/images/B27.webp
    - lib/images/B28.webp
    - lib/images/B29.webp
    - lib/images/B30.webp
    - lib/images/B31.webp
    - lib/images/B32.webp
    - lib/images/B33.webp
    - lib/images/B34.webp
    - lib/images/B35.webp
    - lib/images/B36.webp
    - lib/images/B37.webp
    - lib/images/B38.webp
    - lib/images/B39.webp
    - lib/images/B40.webp
    - lib/images/B41.webp
    - lib/images/B42.webp
    - lib/images/B43.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  generate: true
